# Generated by Django 5.1.3 on 2025-02-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh Giá Sản Phẩm', 'verbose_name_plural': 'Đánh Giá Sản Phẩm'},
        ),
    ]
