# Generated by Django 5.1.3 on 2025-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='avatar',
            field=models.ImageField(blank=True, default='customers/avatars/default.png', null=True, upload_to='customers/avatars/%Y/%m/'),
        ),
    ]
