# Generated by Django 5.1.3 on 2025-02-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customeruser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'Khách Hàng', 'verbose_name_plural': 'Danh sách Khách Hàng'},
        ),
    ]
