# Generated by Django 5.1.6 on 2025-03-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customeruser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
