# Generated by Django 5.1.3 on 2025-02-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh Mục', 'verbose_name_plural': 'Danh Mục'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản Phẩm', 'verbose_name_plural': 'Sản Phẩm'},
        ),
    ]
